### ISSUE TITLE
[Error] windows account that have special characters in path

### ISSUE THREAD

**Issue by CastagnaIT** [peak3d/inputstream.adaptive#244]
A user has reported to me an error that prevents me from starting netflix addon
I think it broke inputstream, because of a special character in path, and falls on netflix addon
can you check it out? thanks

log attached

[kodi.log](https://github.com/peak3d/inputstream.adaptive/files/2975444/kodi.log)

`
2019-03-17 17:12:29.897 T:1012   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: [Error 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\b\xc3\xbcro\\AppData\\Roaming\\Kodi\\cdm/*.*'
                                            Traceback (most recent call last):
                                              File "C:\Users\b��AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py", line 33, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "C:\Users\b��AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "C:\Users\b��AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 253, in router
                                                infoLabels=params.get('infoLabels', {}))
                                              File "C:\Users\b��AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils.py", line 60, in wrapped
                                                result = func(*args, **kwargs)
                                              File "C:\Users\b��AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\Navigation.py", line 313, in play_video
                                                timeline_markers=self._get_timeline_markers(metadata))
                                              File "C:\Users\b��AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\KodiHelper.py", line 909, in play_item
                                                if not is_helper.check_inputstream():
                                              File "C:\Users\b��AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper.py", line 763, in check_inputstream
                                                return self._check_drm()
                                              File "C:\Users\b��AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper.py", line 734, in _check_drm
                                                if not self._has_widevine():
                                              File "C:\Users\b��AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper.py", line 265, in _has_widevine
                                                if self._widevine_path():
                                              File "C:\Users\b��AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper.py", line 108, in _widevine_path
                                                for filename in os.listdir(cls._ia_cdm_path()):
                                            WindowsError: [Error 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\b\xc3\xbcro\\AppData\\Roaming\\Kodi\\cdm/*.*'
                                            -->End of Python script error report<--

`

**Comment by peak3d** [comment]
inputstreamhelper is not my addon.
